/**
 * wave2Descriptions — plain-English look of each Wave 2 1/1 (#8889–8988),
 * written from the actual art (2026-10-02). Wave 2 monkes carry only a
 * "Wave: 02" trait, and a 16×16 pixel portrait alone isn't enough for the
 * model to tell a metal face plate from skin or a chalk outline from fur —
 * tested on #8982: undescribed came out generic, described matched.
 */

export const WAVE2_DESCRIPTIONS: Record<number, string> = {
  8889: "a pastel pink monkey with a hot-pink mullet and mint-white visor shades",
  8890: "a lavender-purple monkey with mint-green visor shades",
  8891: "a desaturated slate-teal monochrome monkey, like a faded old photo",
  8892: "a mint-teal monkey with a mint hair tuft and a purple visor",
  8893: "a monkey with a blonde ponytail, pink visor shades and a pink top",
  8894: "a periwinkle-blue monkey with a small gold crown and a glowing orange visor",
  8895: "an ivory-white monkey with a tan face",
  8896: "a monkey drawn only as a white chalk outline on a black chalkboard",
  8897: "a monkey drawn as a blue engineering blueprint with grid lines, a white face and a crosshair target on its head",
  8898: "a monkey drawn as a bright yellow highlighter sketch with a white face",
  8899: "a glitching black-and-white monkey with a glowing white face and horizontal speed-streak glitch lines",
  8900: "a glitch-art monkey made of rainbow RGB pixel noise with a glowing white face",
  8901: "a gray stone monkey with a chiseled checkered texture, like a carved statue",
  8902: "an olive-gold monochrome monkey with softly glowing pale eyes",
  8903: "a shadowy dark-navy monkey with glowing white eyes and a little sparkle above its head",
  8904: "a cosmic galaxy monkey made of purple and blue stardust with glowing white eyes",
  8905: "a light-green alien monkey with two antennae",
  8906: "a violet-purple monkey with a lavender face and a curly purple antenna",
  8907: "a blue alien monkey with two antennae and glowing white eyes",
  8908: "a dark charcoal monkey with glowing hot-pink horns and a hot-pink visor",
  8909: "a pale sage-green ghostly monkey with big black eyes",
  8910: "an icy pale-blue glowing monkey with a white top-knot",
  8911: "a frosty ice-blue monkey made of ice with orange marks on its cheek",
  8912: "an energy monkey whose whole body glows hot pink, with orange eyes and a pink aura",
  8913: "a glowing bright-red devil monkey with small horns",
  8914: "a classic brown monkey with a tan face",
  8915: "a fire elemental monkey whose whole body is made of flickering orange and yellow flames, with flame hair and glowing yellow eyes",
  8916: "a slime monkey whose whole body is made of glowing translucent neon-green goo",
  8917: "a dark purple monkey with a white bone-mask skull face, white horns and glowing mint eyes",
  8918: "a dusty-mauve monkey with tentacle-like purple hair and a pale face",
  8919: "a dark violet hooded monkey with glowing white eyes",
  8920: "a dark monkey in a black hood with purple and green shutter shades and a cigarette",
  8921: "a dark shadowy monkey in a blue denim jacket with black sunglasses",
  8922: "a dark monkey with a white skull face in a camo jacket",
  8923: "a monkey with a hot-pink mohawk, black sunglasses and a gold earring",
  8924: "a monkey with white anime hair, black shades and a black outfit",
  8925: "a black-haired monkey with shades, a cigarette and a black-and-white outfit",
  8926: "a mauve-gray monkey with dark emo hair and an orange chain",
  8927: "a lavender-haired monkey with black shades in a purple top",
  8928: "a gray monkey with long black hair covering its face",
  8929: "a pale silver-white cat-eared monkey with purple eyes",
  8930: "a monkey with a straw hat with a red band, an open red vest and a big grin, like a pirate captain",
  8931: "a monkey with a yellow and orange racing helmet, black shades and a red-white-yellow racing suit",
  8932: "a monkey in a green hood with a dark gray face mask",
  8933: "a monkey with messy red hair, a big grin and a green vest",
  8934: "a monkey with an orange cap, gray shades and a cigarette in a maroon top",
  8935: "a pitch-black shadow monkey with glowing green eyes",
  8936: "a monkey with brown hair, a white lab coat and mint safety goggles",
  8937: "a dark green camo monkey in a tactical mask with a red exclamation mark above its head",
  8938: "a monkey with spiky black hair, glowing cyan eyes and an orange outfit",
  8939: "a pale olive-green frog-like monkey with a wide pink mouth",
  8940: "a monkey with a red headband and black shades in a black jacket over a red shirt",
  8941: "a bubblegum-pink monkey with a curly pink tuft and a purple collar",
  8942: "a gold-faced monkey with black-and-white split hair and a gold and black outfit",
  8943: "an orange monkey with a tan face, black shades and a buck-toothed grin",
  8944: "a nearly invisible pitch-black shadow monkey",
  8945: "a gray robot monkey with a white and gold helmet and gold trim",
  8946: "a dark gray monkey in a knight's helmet",
  8947: "a monkey with white hair and a gold side braid, black eyes and a white and purple robe",
  8948: "a monkey with a glowing fire-and-blue flame halo around its head and glowing yellow eyes",
  8949: "a gray-green mossy zombie monkey with one glowing red laser eye",
  8950: "a gray-green zombie monkey with glowing red visor eyes",
  8951: "a gray-green zombie monkey with glowing red eyes and a dark tuft",
  8952: "a mossy mauve monkey covered in green moss with a red berry",
  8953: "a pale gray monkey with green moss patches and a pink flower",
  8954: "a cream-white flower monkey with pink petals and pink eyes",
  8955: "a pale pink flower monkey with lime-green eyes and green buds",
  8956: "an olive-green leafy monkey with pink blossoms and pink eyes",
  8957: "a white monkey wearing a red and white spotted mushroom cap",
  8958: "a pale cream monkey with olive-green leafy vines",
  8959: "a dark brown monkey with lavender eyes and little lavender flowers",
  8960: "a glowing golden-yellow banana monkey with a green stem on top",
  8961: "an icy white and blue crystal monkey",
  8962: "an energy monkey whose whole body glows neon magenta with a bright magenta aura",
  8963: "a lava elemental monkey whose whole body is made of glowing molten orange lava with drifting embers",
  8964: "a silver cyborg monkey with a pink glowing eye shooting a red laser beam",
  8965: "a silver robot monkey with a magenta mohawk and green and magenta circuit lights",
  8966: "a silver robot monkey with a green mohawk and a magenta visor",
  8967: "a pale periwinkle robot monkey with white eyes holding a glowing blue wand",
  8968: "a white and red clown-faced monkey with red markings",
  8969: "a monkey in a red and white racing helmet with an orange face",
  8970: "a bright green dragon monkey with small yellow horns and yellow claws",
  8971: "a glowing electric-cyan monkey with spiky white crown points",
  8972: "a pale glowing cyan ghost monkey with sparkles",
  8973: "a white clown monkey with green hair and a red nose",
  8974: "a monkey in a wide orange sombrero with a rainbow band and red glowing eyes",
  8975: "a tan monkey with big red-framed glasses",
  8976: "a monkey with dusty-pink hair, navy shades and an orange jacket",
  8977: "a brown monkey in a white chef's hat and white chef coat",
  8978: "a pale pink monkey with red button eyes and a red nose",
  8979: "a monkey in a yellow hard hat with a cigarette and an orange safety vest",
  8980: "a black-and-white monkey with bold blue, yellow and red Mondrian color blocks",
  8981: "a pastel pink monkey with hot-pink and yellow hair clips",
  8982: "a cyborg monkey with dark navy-black fur and hood, a flat slate-gray metal face plate, glowing lime-green slit eyes, a small red light and a lime-green stripe on its forehead, and lime-green and red indicator lights on its dark chest",
  8983: "a pale bone-white monkey with gray eyes",
  8984: "a pale cream monkey with a brown tuft and a pink tie",
  8985: "a classic brown monkey with a tan face and a little hair tuft",
  8986: "an energy monkey whose whole body glows neon lime green, with orange eyes and a lime aura",
  8987: "a pale white monkey with dark horns and glowing purple eyes",
  8988: "a monkey wearing a round gray astronaut space helmet and a pale suit",
};
